# Generated by Django 5.2 on 2026-01-18 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=200, verbose_name="عنوان المقال"),
                ),
                ("content", models.TextField(verbose_name="المحتوى")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("sugar", "السكري"),
                            ("insulin", "مقاومة الإنسولين"),
                            ("pressure", "ضغط الدم"),
                        ],
                        max_length=20,
                        verbose_name="القسم",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="articles/",
                        verbose_name="صورة المقال",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
